export {
  SignUpSchema,
  type SignUpInput,
  LoginSchema,
  type LoginInput,
  ForgotPasswordSchema,
  type ForgotPasswordInput,
  ResetPasswordSchema,
  type ResetPasswordInput,
  VerifyEmailSchema,
  type VerifyEmailInput,
  PhoneRequestOtpSchema,
  type PhoneRequestOtpInput,
  PhoneVerifyOtpSchema,
  type PhoneVerifyOtpInput,
  EmailRequestOtpSchema,
  type EmailRequestOtpInput,
  EmailVerifyOtpSchema,
  type EmailVerifyOtpInput,
} from "@aurapath/shared";

